use_frameworks!
platform :ios, '14.0'

target 'TCARxSwift_Example' do
  pod 'TCARxSwift', :path => '../'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'TCARxSwift_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
        end
    end
end
